### ISSUE TITLE
sry I can't understand....

### ISSUE THREAD

**Issue by gryphus0173** [NPCat/bad-apple-bot#10]
I was unable to resolve this error.
This is the first time I'm touching the BOT, so it might be an elementary mistake.

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\gryph\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\gryph\badapplediscordplayer.py", line 87, in on_message
    await message.channel.send(frames[int(i)])
  File "C:\Users\gryph\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 935, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\gryph\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by gryphus0173** [comment]
I forgot 
that's happen when I sent !bad Apple

**Comment by ayok01** [comment]
I think it's because I ran "videotoframes.py" and didn't match the output file paths.

https://github.com/NPCat/bad-apple-bot/blob/6c4de5a6395dbc6aebd04c1fc7061d947092dbfc/bad%20apple%20discord%20player.py#L58

In my case, I solved it by adding "./".

**Comment by elite25el** [comment]
Can you drop the code?

**Comment by gryphus0173** [comment]
I check it. but output file path is ok.

**Comment by gryphus0173** [comment]
Sorry.

path = r"C:\Users\gryph\bad apple mp4\frames/frame"+str(i*4)+".jpg" #<--- path to folder containing every frame of the video

I entered collect file path. but it doesn't work.

Unable to find image in C:\Users\gryph\badapplemp4\frames/frame0.jpg

May be this couldn't find frames?

**Comment by gryphus0173** [comment]
Sorry I solved it thank you everyone.
Now working this bot.

**Comment by GriLL714** [comment]
how did you solve this error?
