### ISSUE TITLE
I don't know how to add the bot. How do I use it? I added the bot token and executed the file. Is that all I need to do? Nothing is working and the instructions are unclear. Please help

### ISSUE THREAD

**Issue by bowthawsom66** [NPCat/bad-apple-bot#11]
I don't know how to add the bot. How do I use it? I added the bot token and executed the file. Is that all I need to do? Nothing is working and the instructions are unclear. Please help

**Comment by 1vs9-standart** [comment]
1) Download the folder with bad-apple-boot-main
2) Open the folder with the contents of the bot using Visual Code or any other program
download via **terminal**:
_1.pip install python-time
2.pip install discord.py
3.pip install pillow
4.pip install opencv-python_
3) Change to "bad apple discord player.py"
client.run ('your-token') # <--- Put your bot token here
P:S 
Don't forget to download python right away
4) run "python video to frames.py" wait 1-2 mins (the whole folder will weigh about 200 mb)
5) 
Now you need to specify the path to the frame (example)
path = "C:/ Users/Admin/Desktop/bad-apple-bot-main/frame" + str (i * 4) + ". jpg" # <--- path to folder containing every frame of the video
The prefix "frame" at the end is required
6) Run the bot through the python command: "python bad apple discord player.py"
7) Go to discord and write "! Bad apple" to any channel
After that the bot starts to draw frames (2 frames in 1 second)


Possible error: 
Unable to find image in frames/frameX.jpg <- Wrong path indicated (check point 5 of the instruction)

I apologize right away for my bad english

**Comment by Theofficial-Itzmissunicorn** [comment]
Wha does that mean?

**Comment by Heavytf2** [comment]
> Wha does that mean?

the long and short of it is just make a bot using the developer portal, and then put the bot token into the place that says '
'client.run ('') # <--- Put your bot token here' in python

**Comment by wkdfhr57294** [comment]
What am I supposed to do when I open like this?
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\ST-USER\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event        
    await coro(*args, **kwargs)
  File "c:\Users\ST-USER\Desktop\bad-apple-bot-main\bad apple discord player.py", line 87, in on_message
    await message.channel.send(frames[int(i)])
  File "C:\Users\ST-USER\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 935, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\ST-USER\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
