### ISSUE TITLE
Unable to run with different video

### ISSUE THREAD

**Issue by Nishant-Byte** [NPCat/bad-apple-bot#19]
Can u pls tell me how to run it with different video? Also how to find exact length of video?

I tried to put my video's frame and length and this error showed up 
:gnoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\priti\PycharmProjects\pythonProject3\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\priti\Pictures\bad-apple-bot-main\bad apple discord player.py", line 88, in on_message
    await message.channel.send(frames[int(i)])
  File "C:\Users\priti\PycharmProjects\pythonProject3\venv\lib\site-packages\discord\abc.py", line 935, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\priti\PycharmProjects\pythonProject3\venv\lib\site-packages\discord\http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.

**Comment by akbar-amin** [comment]
I made a [tool](https://github.com/akbar-amin/disctext) that you may find useful :)

**Comment by Hlebuw3k** [comment]
Your video is too big in vertical/horizontal. Discord only allows 2000 letters in 1 message, and you are trying to send more than this. Try making WIDTH parameter lower
