### ISSUE TITLE
Evreything set up, but will not run

### ISSUE THREAD

**Issue by Hakerlol255** [NPCat/bad-apple-bot#24]
Pls help anytime wneh i start bot in discord in cmd i see this error

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\вася\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\вася\Desktop\python\import discord.py", line 87, in on_message
    await message.channel.send(frames[int(i)])
  File "C:\Users\вася\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 1064, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\вася\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by 3y3lone** [comment]
Did you add your discord bot token?
