### ISSUE TITLE
help i really don't know what to do

### ISSUE THREAD

**Issue by ihadabruhmoment** [NPCat/bad-apple-bot#6]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    FrameCapture("bad_apple.mp4")
  File "main.py", line 15, in FrameCapture
    cv2.imwrite("frame%d.jpg" % count, image)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgcodecs/src/loadsave.cpp:753: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

as i am really new to code i think i just got myself in something too hard but i have to finish it cause now it's a personal challenge

**Comment by SomeOrdinaryHuman** [comment]
I can't seem to figure it out either

**Comment by KGTasa** [comment]
Same issue. Any help?

**Comment by melon095** [comment]
Im guessing you are getting this message while using the file video to frames.py. I do not code myself so i can not explain exactly what this means. However to my understanding it has something to do with that opencv is not able to create any more files due to the video ending. You should for now just skip this message and continue with the procedure. Getting a clarification from the creator would always be appreciated.

**Comment by bowthawsom66** [comment]
I don't know how to add the bot. How do I use it? I added the bot token and executed the file. Is that all I need to do? Nothing is working and the instructions are unclear. Please help

**Comment by eimul** [comment]
I think it's because you have the basic opencv module.
Try the more advanced one:
`$ pip install opencv-contrib-python`
**Make sure to uninstall the old OpenCV before installing the new one**

**Comment by 1vs9-standart** [comment]
1) Download the folder with bad-apple-boot-main
2) Open the folder with the contents of the bot using Visual Code or any other program
download via **terminal**:
_1.pip install python-time
2.pip install discord.py
3.pip install pillow
4.pip install opencv-python_
3) Change to "bad apple discord player.py"
client.run ('') # <--- Put your bot token here
P:S 
Don't forget to download python right away
4) run "python video to frames.py" wait 1-2 mins (the whole folder will weigh about 200 mb)
5) Now you need to specify the path to the frame (example)
path = "C:/ Users/Admin/Desktop/bad-apple-bot-main/frame" + str (i * 4) + ". jpg" # <--- path to folder containing every frame of the video
The prefix "frame" at the end is required
6) Run the bot through the python command: "python bad apple discord player.py"
7) Go to discord and write "! Bad apple" to any channel
After that the bot starts to draw frames (2 frames in 1 second)


Possible error: 
Unable to find image in frames/frameX.jpg <- Wrong path indicated (check point 5 of the instruction)

I apologize right away for my bad english
